HostTypeMapping = ('虚拟机', '物理机',)
IPTypeMapping = ('外网', '内网',)
IPStatusMapping = ('已绑定', '空闲',)
DiskStatusMapping = ('挂载', '空闲',)
DiskTypeMapping = ('系统盘', '挂载盘',)
MetricTypeMapping = ('host', 'disk',)
